apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
data:
  JWT_KEY: {{ .Values.JWT_KEY | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: stripe-secret
data:
  STRIPE_KEY: {{ .Values.STRIPE_KEY | b64enc }}