name: deploy-manifests

on:
  push:
    branches: 
      - master
    paths:
      # - 'infra/**'

env:
  GCP_PROJECT_ID: ticketing-devops-hamill
  CLUSTER_NAME: ticketing-staging
  CLUSTER_ZONE: us-central1-c

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v2
      - name: Set up and authenticate to gcloud
        uses: google-github-actions/setup-gcloud@master
        with:
          version: '360.0.0'
          service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }} 
          project_id: ${{ env.GCP_PROJECT_ID }}
      - name: Configure docker for GCP
        run: gcloud --quiet auth configure-docker
      - name: Get GKE credentials
        uses: google-github-actions/get-gke-credentials@main
        with:
          cluster_name: ${{ env.CLUSTER_NAME }}
          location: ${{ ENV.CLUSTER_ZONE }}
          credentials: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
      # Install helm
      - name: Install Helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash
      - name: Upgrade infrastructure and apply Helm charts
        run: |
          helm upgrade ingress-srv-gcp ./infra/ingress-srv-gcp/ \
            --wait
          helm upgrade ticketing-staging ./infra/ticketing-cluster/ \
            --wait
