name: tests-tickets

on:
  pull_request:
    paths:
      - 'tickets/**'

env:
  SERVICE_NAME: tickets

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        run: make tests