name: tests-orders

on:
  pull_request:
    paths:
      - 'orders/**'

env:
  SERVICE_NAME: orders

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        run: make tests
